// COMPRADOR
export const OBTER_COMPRADOR = 'OBTER_COMPRADOR';
export const OBTER_COMPRADOR_ERRO = 'OBTER_COMPRADOR_ERRO';
export const LIMPAR_OBTER_COMPRADOR = 'LIMPAR_OBTER_COMPRADOR';
export const OBTER_COMPRADOR_SUCESSO = 'OBTER_COMPRADOR_SUCESSO';

// SIMULADOR
export const CALCULAR_SIMULACAO = 'CALCULAR_SIMULACAO';
export const CALCULAR_SIMULACAO_ERRO = 'CALCULAR_SIMULACAO_ERRO';
export const LIMPAR_CALCULAR_SIMULACAO = 'LIMPAR_CALCULAR_SIMULACAO';
export const CALCULAR_SIMULACAO_SUCESSO = 'CALCULAR_SIMULACAO_SUCESSO';