// COMPRADOR
export const OBTER_COMPRADOR = 'OBTER_COMPRADOR';
export const LIMPAR_COMPRADOR = 'LIMPAR_OBTER_COMPRADOR';
export const OBTER_COMPRADOR_ERRO = 'OBTER_COMPRADOR_ERRO';
export const OBTER_COMPRADOR_SUCESSO = 'OBTER_COMPRADOR_SUCESSO';

// COMPRADOR
export const SIMULADOR = 'SIMULADOR';
export const LIMPAR_SIMULADOR = 'LIMPAR_SIMULADOR';
export const SIMULADOR_ERRO = 'SIMULADOR_ERRO';
export const SIMULADOR_SUCESSO = 'SIMULADOR_SUCESSO';